sudo: required
services:
  - docker

before_install:
  - docker build -t abubakarwase/devops-practice -f Dockerfile.dev .

script:
  - docker run abubakarwase/devops-practice npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "devops-practice"
  env: "Docker-env"
  bucket_name: ""devops-practice"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
