sudo: required
services:
  - docker

before_install:
  - docker build -t abubakarwase/devops-practice -f Dockerfile.dev .

script:
  - docker run abubakarwase/devops-practice npm run test -- --coverage
